version: '3.1'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: maddytec
      POSTGRES_DB: maddytec_db
      POSTGRES_USER: maddytec
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - 8085:8080

volumes:
  postgres: